### ISSUE TITLE
how to disable multi line 

### ISSUE THREAD

**Issue by xbahaa** [TeleClinic/SmartForm#1]
how to disable multi line, it's working only when i use app:setRegexType="MEDIUM_PASSWORD_VALIDATION"
just on password but on email and the other only appear new line
i use android:imeOptions="actionNext" but not working how can i reach what i want without multi line

**Comment by KarimAbdo** [comment]
For now, this feature is not supported, maybe try to access the edittext in the java file by ".editText" and check if you can do it from there

**Comment by xbahaa** [comment]
binding.fullNameRegistration.editText().setSingleLine(true);
it's working thanks
